apiVersion: v1
kind: Pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: golang
      image: golang:alpine
      command: ["tail", "-f", "/dev/null"]  # this or any command that is bascially a noop is required, this is so that you don't overwrite the entrypoint of the base container
      imagePullPolicy: IfNotPresent # use cache or pull image for agent
      resources:  # limits the resources your build contaiener
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
    - name: docker
      image: docker:20-dind
      command: ["tail", "-f", "/dev/null"]
      tty: true
      imagePullPolicy: IfNotPresent
      #volumeMounts:
      #  - name: docker-socket
      #    mountPath: /var/run/docker.sock # We use the k8s host docker engine
  #volumes:
  #  - name: docker-socket
  #    hostPath:
  #      path: /var/run/docker.sock
